baseURL = "https://alinaozhegova.com"
languageCode = "en-us"
title = "Alina Ozhegova"
theme = "researcher"
enableGitInfo = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 3

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  custom_css = ["css/custom.css"]
  profileImage = "img/alina.png"
  favicon = "favicon.png"

  [params.style]
    fontSize = "12pt"