[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.147.5" 

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 3

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5